CREATE TABLE `blog_login_log` (
  `login_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '登录日志ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
  `user_name` VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  `login_type` VARCHAR(20) NOT NULL COMMENT '登录方式，PASSWORD/EMAIL_CODE',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `login_ip` VARCHAR(128) DEFAULT NULL COMMENT '登录IP',
  `login_location` VARCHAR(255) DEFAULT NULL COMMENT '登录地点',
  `browser` VARCHAR(100) DEFAULT NULL COMMENT '浏览器',
  `os` VARCHAR(100) DEFAULT NULL COMMENT '操作系统',
  `device_info` VARCHAR(255) DEFAULT NULL COMMENT '设备信息',
  `status` CHAR(1) NOT NULL DEFAULT '1' COMMENT '登录状态，1成功0失败',
  `message` VARCHAR(500) DEFAULT NULL COMMENT '结果消息',
  `login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  PRIMARY KEY (`login_log_id`),
  KEY `idx_user_name` (`user_name`),
  KEY `idx_login_type` (`login_type`),
  KEY `idx_status` (`status`),
  KEY `idx_login_time` (`login_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';

CREATE TABLE `blog_oper_log` (
  `oper_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作日志ID',
  `title` VARCHAR(100) NOT NULL COMMENT '模块标题',
  `business_type` VARCHAR(30) NOT NULL COMMENT '业务类型，INSERT/UPDATE/DELETE/OTHER',
  `method` VARCHAR(200) DEFAULT NULL COMMENT '方法名称',
  `request_method` VARCHAR(10) DEFAULT NULL COMMENT '请求方式',
  `oper_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人',
  `oper_url` VARCHAR(255) DEFAULT NULL COMMENT '请求URL',
  `oper_ip` VARCHAR(128) DEFAULT NULL COMMENT '操作IP',
  `oper_location` VARCHAR(255) DEFAULT NULL COMMENT '操作地点',
  `oper_param` TEXT COMMENT '请求参数',
  `json_result` TEXT COMMENT '返回结果',
  `status` CHAR(1) NOT NULL DEFAULT '1' COMMENT '操作状态，1成功0失败',
  `error_msg` VARCHAR(2000) DEFAULT NULL COMMENT '错误消息',
  `cost_time` BIGINT DEFAULT 0 COMMENT '耗时，单位毫秒',
  `oper_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`oper_log_id`),
  KEY `idx_title` (`title`),
  KEY `idx_business_type` (`business_type`),
  KEY `idx_oper_name` (`oper_name`),
  KEY `idx_status` (`status`),
  KEY `idx_oper_time` (`oper_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
